on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} desktop/build/libs/SpindDesktop.jar
          mv android/build/output/apk/release/android-release-unsigned.apk android/build/output/apk/release/SpindAndroid.apk
          gh release upload ${{ github.ref_name }} android/build/libs/SpindDesktop.jar
