on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          chmod +x ./gradlew
          ./gradlew desktop:build
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} desktop/build/libs/SpindDesktop.jar
  publish-windows:
    runs-on: windows-latest
    environment: github-actions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Wix Toolset
        run: choco install wixtoolset
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          chmod +x ./gradlew
          .\gradlew desktop:build
          .\gradlew jpackage
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv desktop/build/Spind-*.msi desktop/build/SpindWindows.msi
          gh release upload ${{ github.ref_name }} desktop/build/SpindWindows.msi
  publish-android:
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          chmod +x ./gradlew
          ./gradlew android:build
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv android/build/outputs/apk/release/android-release-unsigned.apk android/build/outputs/apk/release/SpindAndroid.apk
          gh release upload ${{ github.ref_name }} android/build/outputs/apk/release/SpindAndroid.apk
